version: 2
jobs:
  build:
    environment:
      - GOPATH: /home/circleci/go
        GO111MODULE: "on"
    docker:
      - image: circleci/golang:1.12
    working_directory: /home/circleci/go/src/github.com/guni1192/couml
    steps:
      - run: echo 'export PATH=${GOPATH}/bin/:${PATH}' >> $BASH_ENV
      - run: echo $GOPATH
      - checkout
      - run: GO111MODULE=off go get -u github.com/golang/lint/golint
      - run: go build -v -o bin/couml github.com/guni1192/couml/cmd
      - run: go vet ./...
      - run: golint -set_exit_status ./...
      - run: "! go fmt ./... 2>&1 | read"
      - run: go test -v ./...

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
